#!/bin/bash
export PORT=9000
if [ -x /var/lang/node18/bin/node ]; then
  exec /var/lang/node18/bin/node app.js
fi
if [ -x /var/lang/node20/bin/node ]; then
  exec /var/lang/node20/bin/node app.js
fi
if [ -x /var/lang/node16/bin/node ]; then
  exec /var/lang/node16/bin/node app.js
fi
exec node app.js
